 name: CI Java 21

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      # Ejercicio 1 + parte de 2: unit tests con Surefire
      - name: Unit tests (Surefire)
        run: ./mvnw -B -ntp clean test | tee unit-build.log

      # Ejercicio 2: segundo tipo de prueba (integration) con Failsafe
      # Sin perfiles raros: ejecutamos integration-test + verify explícitos
      - name: Integration tests (Failsafe)
        run: ./mvnw -B -ntp failsafe:integration-test failsafe:verify | tee it-build.log

      # Reporte HTML (incluye los directorios de surefire y failsafe)
      - name: Generate HTML test report
        run: |
          ./mvnw -B -ntp surefire-report:report \
            -Daggregate=true \
            -DreportsDirectories="target/surefire-reports,target/failsafe-reports" || true

      # Evidencias: logs + XML/HTML
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-test-reports
          path: |
            unit-build.log
            it-build.log
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
            **/target/site/surefire-report.html
          if-no-files-found: warn
