name: CI Java 21

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Asegura mvnw ejecutable en Linux y corrige CRLF si aparece
      - name: Make mvnw runnable (LF + +x)
        run: |
          sed -i 's/\r$//' mvnw || true
          chmod +x mvnw

      # Ejecuta unit + integration (Failsafe recoge **IT)
      - name: Build + Unit & Integration tests
        run: ./mvnw -B -ntp clean verify | tee build.log

      # Sube evidencias
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-test-reports
          path: |
            build.log
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
          if-no-files-found: warn
