  name: CI Java 21

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      # Unit tests (Surefire)
      - name: Unit tests
        run: ./mvnw -B -ntp clean test | tee unit-build.log

      # Integration tests (Failsafe: ejecuta *IT en verify)
      - name: Integration tests
        run: ./mvnw -B -ntp verify | tee it-build.log

      # Evidencias (logs + XML)
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-test-reports
          path: |
            unit-build.log
            it-build.log
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
