name: CI Java 21

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      # Unit tests (Surefire)
      - name: Unit tests (Surefire)
        run: ./mvnw -B -ntp clean test | tee unit-build.log

      # Integration tests (Failsafe con perfil it)
      - name: Integration tests (Failsafe, profile it)
        run: ./mvnw -B -ntp verify -Pit | tee it-build.log

      # (Opcional) Reporte HTML (incluye surefire y failsafe)
      - name: Generate HTML reports
        run: |
          ./mvnw -B -ntp surefire-report:report \
            -Daggregate=true \
            -DreportsDirectories="target/surefire-reports,target/failsafe-reports" || true

      # Evidencias: logs + XML/TXT + HTML
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-test-reports
          path: |
            unit-build.log
            it-build.log
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
            **/target/site/**
          if-no-files-found: warn
